language: python
python:
  - "3.5"

# Set up CouchDB

services:
  - couchdb
before_script:
  - curl -X PUT localhost:5984/pythonista-cloud

# Test and report coverage

install:
  - pip install coveralls
  - pip install -r requirements.txt
script:
  - coverage run --source=application test.py
after_success:
  coveralls
